  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "About"
  weight = 200
  identifier = "about"
  url = "/about/"

  [[main]]
  name = "Portfolio"
  weight = 300
  identifier = "portfolio"
  url = "/portfolio/"

  [[main]]
  name = "Posts"
  weight = 400
  identifier = "posts"
  url = "/posts/"


  [[main]]
  name = "Contact"
  weight = 500
  identifier = "contact"
  url = "/contact/"


#  [[main]]
#  name = "Accomplishments"
#  weight = 600
#  identifier = "accomplishments"

#  [[main]]
#  name = "Awards"
#  weight = 610
#  identifier = "awards"
#  url = "/awards/"
#  parent = "accomplishments"  

#  [[main]]
#  name = "Certifications"
#  weight = 620
#  identifier = "certifications"
#  url = "/certifications/"
#  parent = "accomplishments"

  [[footer]]
  name = "copyright"
  weight = 1
  identifier = "copyright"
  url = "/copyright/"